name: "Update Local Repo and Restart PM2 On Merge"

on:
  push:
    branches:
      - production

jobs:
  update_local_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}



      - name: Checkout 'production' branch
        uses: actions/checkout@v2
        with:
          ref: production 

      - name: Restart PM2
        run: |
          pm2 restart melodiverse-client
          pm2 restart melodiverse-server
